### ISSUE TITLE
Standard players does not get updated upon joining a server

### ISSUE THREAD

**Issue by Goldenschmidt** [EtiTheSpirit/TheOriMod#16] opened 2023-01-29 01:11 UTC
**What happens?**
When a player joins a server, and finds a player who is supposedly in Spirit state, they will just see the standard form of the player.
Only way to update this, is for the spirit player to be set themselves as `True` with the command. No need to set False first.

**How do I cause it?**
Be in a server with the mod. Set your own state to Spirit. Let a friend join and look at you. 

**Is this bug so bad that you find it nearly impossible to play?**
Nope. Not that big of an issue.

**Log file**
None available at this time of writing.

**Comment by EtiTheSpirit** [comment] 2023-01-29 09:57
I can't reproduce this error.

I tested this in three ways:
1. Joined a friend in another dimension by going to that dimension
2. Joined a friend while standing next to them
3. Left the server after going away from my friend (out of entity range), rejoined, and walked back to them

In all cases, we saw each other as spirits. Perhaps there is another cause, or some factor I am missing?

**Comment by Goldenschmidt** [comment] 2023-01-29 10:02
That, or it could be another mod interfering..
Did find one mod that would crash the client if you as much as had the Hardlight shield in your inventory. Shield Expansion.

I will run more test with this issue. (Not the one I just mentioned, of course)

**Comment by EtiTheSpirit** [comment] 2023-01-29 11:45
Yeah there is a good chance its other mods (or out of date versions) causing incompatibility. I ended up testing the latest build of Shield Expansion in my dev environment and it worked fine, the only error is that the hit sound did not work properly.

**Comment by Goldenschmidt** [comment] 2023-01-29 14:14
> Yeah there is a good chance its other mods (or out of date versions) causing incompatibility. I ended up testing the latest build of Shield Expansion in my dev environment and it worked fine, the only error is that the hit sound did not work properly.

Yup. Added a new issue, regarding this. #17

**Comment by Goldenschmidt** [comment] 2023-01-29 17:42
> I can't reproduce this error.
> 
> I tested this in three ways:
> 
>     1. Joined a friend in another dimension by going to that dimension
> 
>     2. Joined a friend while standing next to them
> 
>     3. Left the server after going away from my friend (out of entity range), rejoined, and walked back to them
> 
> 
> In all cases, we saw each other as spirits. Perhaps there is another cause, or some factor I am missing?

It happened again.
If you couldn't reproduce it with just the Spirit mod alone, it must be something with a mod included.
Will do more testing with it. But will take some time to find the culprit, with the limitations I'm having. If I had another account at my disposal, I could do this at lightning speed.

**Comment by EtiTheSpirit** [comment] 2023-02-05 12:01
For time time being I am going to close this issue, given that I can't reproduce it at all. If it occurs again, please leave a comment here and I can reopen it.

**Closed as not planned by EtiTheSpirit** 2023-02-05 12:01 UTC
Labels: bug, needs more info

**Comment by Goldenschmidt** [comment] 2023-02-05 23:24
> For time time being I am going to close this issue, given that I can't reproduce it at all. If it occurs again, please leave a comment here and I can reopen it.

Apparently, with 2.0.1., this does no longer happen. So.. you must've fixed it somehow.
Friend reported seeing me in my spirit form, even if I never used the command to set my state.
So... guess it was fixed?
