### ISSUE TITLE
Mod is incompatible with Create, causes a crash on startup.

### ISSUE THREAD

**Issue by Goldenschmidt** [EtiTheSpirit/TheOriMod#2] opened 2023-01-05 19:30 UTC
**What happens?**
The server crashes with the error: Mod loading error has occurred

**How do I cause it?**
Install a dedicated server on your PC using the Forge installer. Run the server once to set true in the EULA, and then boot the server up again the second time. Close the server, and install the Spirit mod. On top of this, install the Create mod and its dependency "Flywheel Forge"

**Is this bug so bad that you find it nearly impossible to play?**
Clients can play this combination just fine. Dedicated servers just simply crashes.

**Log file**
[debug.log](https://github.com/EtiTheSpirit/TheOriMod/files/10355154/debug.log)

**Comment by Goldenschmidt** [comment] 2023-01-11 17:53
Tested it with the latest RC2 update.
This is the latest Debug for that: 
[debug.log](https://github.com/EtiTheSpirit/TheOriMod/files/10394792/debug.log)

**Comment by EtiTheSpirit** [comment] 2023-01-13 10:35
This issue is related to create it seems. It was buried in the log and it took me a bit to find it, but here, on line 1716:
```
...
[11jan.2023 18:52:00.294] [main/ERROR] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Create (create) has failed to load correctly
...
]
```

Does this issue occur when my mod is uninstalled? This may be a compatibility problem with Create if so. It was an issue with my mod too before and that issue was fixed. This one is being raised by Create instead, as you can see.

Edit: For the time being I will classify this as invalid.

**Comment by Goldenschmidt** [comment] 2023-01-13 14:31
I did a run with only create, and it launched fine.
Here is the Debug.log that also shows that it detects objects and items that no longer exists (Ori mod stuff) as it loads up the world and injects Create mod stuff.
[debug.log](https://github.com/EtiTheSpirit/TheOriMod/files/10412368/debug.log)

**Comment by EtiTheSpirit** [comment] 2023-01-13 17:11
Yeah, then this issue is caused by incompatibility with Create. This is not something I can look into right now as it would require collaboration with the Create developer/team to nail down exactly what has gone wrong. Sorry.

The issue will be left open until it is fixed.

**Comment by EtiTheSpirit** [comment] 2023-01-13 18:15
Okay, status update. Someone from the Forge discord lent me a hand. It is an issue I can fix. It will be fixed in RC3.

**Closed as completed** 2023-01-16 10:07 UTC
Labels: bug, fixed in dev
