### ISSUE TITLE
Crash when equipping Hardlight Shield with Good Ending mod

### ISSUE THREAD

**Issue by Goldenschmidt** [EtiTheSpirit/TheOriMod#17] opened 2023-01-29 13:37 UTC
**What happens?**
Getting the Hardlight Shield into your inventory will crash your game, if you have Good Ending mod installed.

**How do I cause it?**
Have both the Ori mod and the Good Ending mod installed, and give yourself the Light Shield. Boom! Crash.

**Is this bug so bad that you find it nearly impossible to play?**
Nope. But the moment you acquire the shield, your own hope to get back into the save again would be to use the NBTEditor.

**Log file**
[crash-2023-01-29_14.33.32-server.txt](https://github.com/EtiTheSpirit/TheOriMod/files/10529878/crash-2023-01-29_14.33.32-server.txt)
[crash-2023-01-29_14.33.35-client.txt](https://github.com/EtiTheSpirit/TheOriMod/files/10529879/crash-2023-01-29_14.33.35-client.txt)

**Comment by EtiTheSpirit** [comment] 2023-01-29 20:48
This is a bug in Good Ending itself. I have taken the liberty of moving this report to their repository on your behalf as I did some reading in their source code to isolate the cause with the help of your crash log. You can check the issue's status here: [Good Ending :: Issue #7](https://github.com/0rc1nus/GoodEnding/issues/7)). As such, this issue will be closed. 

After having a look at their source code, you should be able to bypass this issue by giving yourself a shield that has a tag on it. You can use the /give command like this to fix the bug: `/give @s orimod:light_shield{Damage:0}`

Admittedly, part of this issue *is* caused by the lack of a `Damage` field on the Hardlight Shield, which is part of why it is indestructible (adding the tag alone will not help). This will be fixed in the next update of my mod, but this is your workaround for now. I will file a new issue myself for this problem, so no worries about doing that.

**Closed as not planned by EtiTheSpirit** 2023-01-29 20:48 UTC
Labels: bug, wontfix
