### ISSUE TITLE
"Only eat plant-based foods" crashes the server

### ISSUE THREAD

**Issue by Goldenschmidt** [EtiTheSpirit/TheOriMod#20] opened 2023-02-03 12:32 UTC
**What happens?**
Trying to eat any kind of meat doesn't just stop you from eating it. It literally crashes the entire server. Even if you aren't in the Spirit form.

**How do I cause it?**
Enable the `only_eat_plants` setting, and launch the server.
When in, whether or not you're in the Spirit state, try to eat any kind of meat. Even if rotten flesh. Boom, crash.

**Is this bug so bad that you find it nearly impossible to play?**
It crashes the server. If you want to have this setting enabled, it can be difficult to avoid the crash.

**Log file**
[debug.log](https://github.com/EtiTheSpirit/TheOriMod/files/10578864/debug.log)

**Comment by EtiTheSpirit** [comment] 2023-02-04 10:13
This issue is caused by the same error as #18 so it will be fixed when that is fixed.

**Comment by EtiTheSpirit** [comment] 2023-02-05 11:59
Fixed in 2.0.1

**Closed as completed by EtiTheSpirit** 2023-02-05 11:59 UTC
Labels: bug, fixed in dev
